### ISSUE TITLE
lsp-mode doesn't work in docker exec

### ISSUE THREAD

**Issue by robnagler** [biviosoftware/home-env#76] opened 2023-05-10 00:05 UTC
Get's prompted for something.

**Comment by e-carlin** [comment] 2023-05-15 16:32
Can you give me steps to reproduce? I started a docker container, exec'd in, started emacs, started lsp-mode, and was able to use lsp-jump-to-definition.

**Comment by robnagler** [comment] 2023-05-15 17:29
> Unable to find installed server supporting this file. The following servers could be installed automatically:

**Comment by e-carlin** [comment] 2023-05-15 19:35
Copied from our other thread:

That's normal. lsp-mode needs a language server to be installed. If you hit tab it will give you options. For python I use pyright. For js/ts I use ts-ls
I searched some time ago for a way to hardcode this but didn't find a good option

Should I find a way to hardcode or call it good?

**Comment by robnagler** [comment] 2023-05-16 00:13
I think lsp-mode should be off by default. You can turn it on with a pre-bivio-init.el. One option is to install it in Docker images by default if it is not already there, and have it turn off lsp-mode with the default being on if you don't explicitly turn it off (normal users).

**Comment by e-carlin** [comment] 2023-05-16 14:18
> One option is to install it in Docker images by default

Install the language server or pre-bivio-init.el?

> should be off by default ... default being on 

Should lsp-mode be off or on by default?

**Comment by robnagler** [comment] 2023-05-16 15:19
> Install the language server or pre-bivio-init.el?

I meant pre-bivio-init.el

> Should lsp-mode be off or on by default?

A design decision. I think the net effect for exec'ing into a docker container should be no prompt or lsp compiles. Usually this happens when something is already strange going in sysadmin on prod, and this just adds to the confusion (at least for me). 

As to how to accomplish this, I made two suggestions. I'm not sure which one is best.

**Comment by e-carlin** [comment] 2023-06-28 17:38
We ran into this again today. Here is what I'm going to try to implement:

- lsp-mode is off by default
- User can set a flag in pre-bivio-init.el to enable
- If lsp is enabled then upon opening of a python or js/ts file it will try to install the needed language server if not already installed. pyright for python and ts-ls for js/ts. 
- These servers require some pre-requisites. I'll need to understand them better. For ts-ls node.js and npm need to be available. I think pyright can come from npm or pypi. I imagine installing from npm will be easier since we can install globally and don't have to worry about python virtual environments. But, it is a little goofy to require node.js/npm for working on python. It may be that for the pyright to work right (ex jump to definition) it needs to be in the current virtual environment.

**Comment by robnagler** [comment] 2023-06-28 19:20
Thanks, and sounds good.

If it is off by default, then let the error just percolate. The user has to be explicit to turn it on so they should follow the complete install instructions (wherever those are).

**Comment by e-carlin** [comment] 2023-07-31 15:41
I read about eglot yesterday https://git.savannah.gnu.org/cgit/emacs.git/tree/etc/EGLOT-NEWS?h=emacs-29 . It is a standalone LSP package that was merged into emacs. I'm going to investigate it and if it works then switch to it and implement the above plan.

**Comment by e-carlin** [comment] 2024-01-30 21:24
Made obsolete by https://github.com/biviosoftware/home-env/issues/110

**Closed by e-carlin** 2024-01-30 21:24 UTC
